---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ttwings.
--- DateTime: 2018/3/9 1:16
---
local actors = {}

actors.player = {x = 5,y = 5,hp = 8,turn = 100,name = "东方",action = "行动",
          color = colors.player,skill1={name="长拳",exp=1},skill2={name="罗汉拳",exp=1},skill3={name="通背拳",exp=1},skill4={name="伏虎拳",exp=1}}
actors.enemy = {x = 7,y = 7,hp = 10,turn = 90,name = "赖三",action = "行动",
         color = colors.enemy}